builds:
  - env:
      - CGO_ENABLED=0
  - binary: skynet
    main: main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarm: 6
      - goos: windows
        goarm: 7
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{.Tag}}_{{- .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"

release:
  draft: true
  prerelease: auto
  target_commitish: "{{ .Commit }}"
  name_template: "{{.Version}}"
