builds:
  - skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  draft: false
  mode: append
  extra_files:
    - glob: ./build/**/*
    - glob: ./build/checksums.txt
  name_template: "Release {{.Tag}}"
