#!/usr/bin/env bash

: << !
Name: post-commit
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2023-10-08 13:57:32

Description: Git hook，commit后获取commit hash

Attentions:
-

Depends:
-
!

# 获取最新commit哈希值
commit_hash=$(git rev-parse --short HEAD)

# 复制哈希值到系统剪贴板（-n参数表示不换行）
echo -n "$commit_hash" | xsel --clipboard --input
