name: "Go Build and Release by GoReleaser"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: "Install gl"
        run: sudo apt install libgl1-mesa-dev
      - name: "Install MinGW"
        uses: egor-tensin/setup-mingw@v2.2.0
      - name: "MinGW version"
        run: x86_64-w64-mingw32-gcc -dumpversion
      - name: "Run GoReleaser"
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
